### ISSUE TITLE
"can't give argument to non-function" error while installing servicex locally

### ISSUE THREAD

**Issue by sudo-panda** [ssl-hep/ServiceX#215]
I am using minikube to run a Kubernetes cluster on my PC.

When using the command :

```
helm install -g -f demo-values.yaml ssl-hep/servicex
```

I get the following error:

```
Error: template: servicex/charts/minio/templates/deployment.yaml:198:20: executing "servicex/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
```

Is there any known solutions to this error.

**Comment by AndrewEckart** [comment]
Thanks for the report! Here's my summary of this issue.

#### Cause
This is an upstream error in the Minio chart:
https://github.com/helm/charts/issues/21446

It was fixed in Minio 5.0.16 (March 17, 2020):
https://github.com/helm/charts/pull/21447

However, this fix won't be applied if your local version of the chart is out of date.

#### Temporary fix for @sudo-panda 

To fix it, try running `helm repo update`. 

To confirm that the update worked, run `helm show chart stable/minio` and check that the version is 5.0.16 or later:
```bash
$ helm show chart stable/minio
apiVersion: v1
appVersion: master
deprecated: true
description: DEPRECATED MinIO is a high performance data infrastructure for machine
  learning, analytics and application data workloads.
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
name: minio
sources:
- https://github.com/minio/minio
version: 5.0.33
```
You should now be able to make deployments without running into this issue.

#### Permanent fix (@BenGalewsky)
To permanently fix this, we need to (at minimum) update the ServiceX chart dependencies in `requirements.yaml` to require version 5.0.16+ of the Minio chart.

On a related note, the Minio developers have migrated their chart from the [stable](https://github.com/helm/charts) Helm repo (which has been deprecated by Google) to their own Helm [repo](https://github.com/minio/charts) (called `minio`) at https://helm.min.io/.

The latest version of the Minio chart available from `stable` is currently 5.0.33, which is deprecated. The `minio` repo contains version 8.0.0 of the Minio chart, which is the latest version. This would be a good opportunity to use the new Helm repo, so we can continue to get the latest version of the chart. To do this, we can update `requirements.yaml` with:
```
  - name: minio
    version: 8.0.*
    repository: https://helm.min.io/
    condition: objectStore.enabled
```

**Comment by sudo-panda** [comment]
@AndrewEckart I tried these methods to resolve the issue but none of them worked

### By following DEPLOYMENT.md
When I run 
```
helm dependency update
```
it grabs the 5.0.33 version itself when I look into the `servicex/charts` folder but the error in the issue still appears when I tried to install


### By following temporary fix
When I tried to run 
```
helm show chart stable/minio
``` 
it gives me 
```
Error: failed to download "stable/minio"
```

### By following permanent fix
I tried out the permanent fix locally too but the error still persists even though 
```
helm dependency update
```
grabs version `8.0.0`.

### An observation
The weird part is that I deleted the files in `servicex/charts` and ran 
```
helm install -g -f demo-values.yaml ssl-hep/servicex
``` 
without running 
```
helm dependency update servicex
``` 
first and the error 
```
Error: template: servicex/charts/minio/templates/deployment.yaml:198:20: executing "servicex/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
``` 
still appeared.

**Comment by AndrewEckart** [comment]
> @AndrewEckart I tried these methods to resolve the issue but none of them worked
> 
> ### By following DEPLOYMENT.md
> When I run
> 
> ```
> helm dependency update
> ```
> 
> it grabs the 5.0.33 version itself when I look into the `servicex/charts` folder but the error in the issue still appears when I tried to install
> 
> ### By following temporary fix
> When I tried to run
> 
> ```
> helm show chart stable/minio
> ```
> 
> it gives me
> 
> ```
> Error: failed to download "stable/minio"
> ```
> 
> ### By following permanent fix
> I tried out the permanent fix locally too but the error still persists even though
> 
> ```
> helm dependency update
> ```
> 
> grabs version `8.0.0`.
> 
> ### An observation
> The weird part is that I deleted the files in `servicex/charts` and ran
> 
> ```
> helm install -g -f demo-values.yaml ssl-hep/servicex
> ```
> 
> without running
> 
> ```
> helm dependency update servicex
> ```
> 
> first and the error
> 
> ```
> Error: template: servicex/charts/minio/templates/deployment.yaml:198:20: executing "servicex/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
> ```
> 
> still appeared.

Hmm, I think I spoke too soon, my apologies.

When you run `helm install -g -f demo-values.yaml ssl-hep/servicex` it pulls the ServiceX chart from our own helm repo, so any local changes you make won't matter. My guess is that it's not working because the latest version of the ServiceX chart published in our own helm repo (chart version 0.4.0) contains a `requirements.lock` file with Minio 5.0.6 instead of 5.0.33. I pulled it down to make sure, and that is the case.

It looks like Ben already updated `requirements.lock` in #204, but we still need to publish an updated version of the ServiceX chart with the fix. In the meantime, you can avoid the helm repo business entirely by cloning this repo and running `helm install -g -f demo-values.yaml servicex` from the top directory. This bypasses our ssl-hep chart repo and uses the local copy of the chart inside the servicex folder, so any changes are reflected immediately (though you shouldn't need to make any if you clone our main branch).

**Comment by sudo-panda** [comment]
> In the meantime, you can avoid the helm repo business entirely by cloning this repo and running `helm install -g -f demo-values.yaml servicex` from the top directory. This bypasses our ssl-hep chart repo and uses the local copy of the chart inside the servicex folder, so any changes are reflected immediately (though you shouldn't need to make any if you clone our main branch).

@AndrewEckart thats what I have been doing all along.

**Comment by sudo-panda** [comment]
@AndrewEckart thanks for the help I needed to remove repo from my helm repo list before installing the locally cloned repo. It works now.
